version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: toxicbakery/alpine-glibc-android:release-ndk-1.1.1

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: "Build" 
          command: ./gradlew build

